# Generated by Django 5.2.11 on 2026-02-28 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_coach_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_id', models.CharField(blank=True, help_text='생성자 ID', max_length=50, null=True)),
                ('update_id', models.CharField(blank=True, help_text='수정자 ID', max_length=50, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='생성 일시')),
                ('update_date', models.DateTimeField(auto_now=True, help_text='수정 일시')),
                ('use_yn', models.CharField(default='Y', help_text='사용 여부 (Y/N)', max_length=1)),
                ('question_text', models.TextField(help_text='질문 텍스트')),
                ('slot_type', models.CharField(choices=[('technical', '기술'), ('motivation', '지원동기'), ('collaboration', '협업'), ('problem_solving', '문제해결'), ('growth', '성장'), ('general', '공통')], db_index=True, default='general', help_text='슬롯 유형', max_length=20)),
                ('company', models.CharField(blank=True, db_index=True, default='', help_text='기업명', max_length=100)),
                ('job', models.CharField(blank=True, db_index=True, default='', help_text='직무', max_length=100)),
                ('category', models.CharField(blank=True, default='', help_text='카테고리 (OS, Network, ML 등)', max_length=100)),
                ('source', models.CharField(blank=True, db_index=True, default='', help_text='데이터 소스', max_length=30)),
                ('language', models.CharField(choices=[('ko', '한국어'), ('en', '영어')], default='ko', help_text='언어', max_length=5)),
                ('region', models.CharField(blank=True, default='korea', help_text='지역', max_length=20)),
                ('answer_text', models.TextField(blank=True, default='', help_text='답변 텍스트')),
                ('answer_summary', models.TextField(blank=True, default='', help_text='답변 요약')),
                ('period', models.CharField(blank=True, default='', help_text='채용시기 (2024년 상반기)', max_length=20)),
                ('employment_type', models.CharField(blank=True, default='', help_text='채용유형 (신입/인턴/경력)', max_length=10)),
                ('interview_type', models.CharField(blank=True, default='', help_text='면접유형 (일반/인성/압박/임원/PT)', max_length=20)),
                ('is_it_job', models.BooleanField(blank=True, help_text='IT 직무 여부', null=True)),
                ('c_idx', models.IntegerField(blank=True, help_text='잡코리아 기업 ID', null=True)),
                ('difficulty', models.CharField(blank=True, default='', help_text='난이도', max_length=20)),
                ('keywords', models.JSONField(blank=True, default=list, help_text='키워드 태그')),
            ],
            options={
                'verbose_name': '면접 질문',
                'verbose_name_plural': '면접 질문 뱅크',
                'db_table': 'question_bank',
                'ordering': ['-create_date'],
                'indexes': [models.Index(fields=['company', 'slot_type', 'job'], name='idx_company_slot_job'), models.Index(fields=['slot_type', 'source'], name='idx_slot_source'), models.Index(fields=['company', 'interview_type'], name='idx_company_interview')],
            },
        ),
    ]
